module.exports = {
  CHANGE_FILTER: 'CHANGE_FILTER',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_ITEMS_PER_PAGE_COUNT: 'CHANGE_ITEMS_PER_PAGE_COUNT',
  CHANGE_ORDER: 'CHANGE_ORDER',
  LOAD_DATA: 'LOAD_DATA'
};
